-- ============================================================================
--  Hogwarts Rice — Hyprland Lua config  (live-session build)
--  This Hyprland build loads hyprland.lua preferentially.  The canonical,
--  version-robust classic config lives in hyprland.conf (used by install.sh
--  on fresh systems).  The two are kept in sync.
-- ============================================================================
local HOME = os.getenv("HOME") or "/home/scushi"
local CONFIG = (os.getenv("XDG_CONFIG_HOME") or HOME .. "/.config")

-- Active palette (generated by apply-theme.sh).  Fall back if absent.
local ok, C = pcall(dofile, CONFIG .. "/hypr/colors.lua")
if not ok then
    C = { active_border = "rgba(c0392bcc)", inactive_border = "rgba(331a2099)",
          shadow = "rgba(0a050699)", bg = "rgba(140b0dff)",
          accent = "#c0392b", accent2 = "#d4af37" }
end

-- Animation mode (snappy | whimsy).
local mode_file = io.open((os.getenv("XDG_STATE_HOME") or HOME .. "/.local/state") .. "/hogwarts/mode", "r")
local MODE = (mode_file and mode_file:read("*l")) or "snappy"
if mode_file then mode_file:close() end

hl.config({ autogenerated = false })

-- --- Programs ---------------------------------------------------------------
local terminal    = "kitty"
local fileManager = "dolphin"
local launcher    = CONFIG .. "/rofi/scripts/launcher.sh"
local keybinds    = CONFIG .. "/rofi/scripts/keybinds.sh"
local settings    = CONFIG .. "/rofi/scripts/settings.sh"
local power       = CONFIG .. "/rofi/scripts/power.sh"

-- --- Monitor ----------------------------------------------------------------
hl.monitor({ output = "", mode = "1920x1080@60", position = "0x0", scale = "1" })

-- --- Environment ------------------------------------------------------------
local envs = {
    { "XDG_CURRENT_DESKTOP", "Hyprland" }, { "XDG_SESSION_TYPE", "wayland" },
    { "XDG_SESSION_DESKTOP", "Hyprland" }, { "QT_QPA_PLATFORM", "wayland" },
    { "QT_WAYLAND_DISABLE_WINDOWDECORATION", "1" }, { "GDK_BACKEND", "wayland" },
    { "MOZ_ENABLE_WAYLAND", "1" }, { "WLR_NO_HARDWARE_CURSORS", "1" },
    { "XCURSOR_SIZE", "24" }, { "HYPRCURSOR_SIZE", "24" },
    { "_JAVA_AWT_WM_NONREPARENTING", "1" },
}
for _, e in ipairs(envs) do hl.env(e[1], e[2]) end

-- --- Look & feel ------------------------------------------------------------
hl.config({
    general = {
        gaps_in = 4, gaps_out = 8, border_size = 2, layout = "dwindle",
        resize_on_border = true, allow_tearing = false,
        col = {
            active_border   = { colors = { C.active_border, C.active_border2 or C.inactive_border }, angle = 45 },
            inactive_border = C.inactive_border,
        },
    },
    decoration = {
        rounding = 14, rounding_power = 2,
        active_opacity = 0.98, inactive_opacity = 0.92, fullscreen_opacity = 1.0,
        shadow = { enabled = true, range = 18, render_power = 3, color = 0xaa000000 },
        blur = {
            enabled = true, size = 12, passes = 3, xray = true,
            new_optimizations = true, brightness = 1.0, noise = 0.015,
            contrast = 1.0, popups = true, popups_ignorealpha = 0.6,
        },
    },
    dwindle = { preserve_split = true, smart_resizing = true },
    master  = { new_status = "slave", mfact = 0.55 },
    misc = {
        disable_hyprland_logo = true, disable_splash_rendering = true,
        force_default_wallpaper = 0, vrr = 1,
        focus_on_activate = true, initial_workspace_tracking = false,
        animate_manual_resizes = false,
    },
    input = {
        kb_layout = "us", repeat_rate = 40, repeat_delay = 300,
        numlock_by_default = true, follow_mouse = 1, sensitivity = 0,
        touchpad = { natural_scroll = true, tap_to_click = true },
    },
})

-- --- Curves + animations (mode-dependent) -----------------------------------
if MODE == "whimsy" then
    -- Bouncy, magical.
    hl.curve("whimsy_bounce",   { type = "bezier", points = { {0.34, 1.56}, {0.64, 1} } })
    hl.curve("whimsy_soft",     { type = "bezier", points = { {0.22, 1}, {0.36, 1} } })
    hl.curve("whimsy_overshoot",{ type = "bezier", points = { {0.05, 0.9}, {0.1, 1.25} } })
    hl.curve("whimsy_float",    { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })
    hl.curve("whimsy_glide",    { type = "bezier", points = { {0.45, 0}, {0.15, 1} } })
    hl.animation({ leaf = "windows",       enabled = true, speed = 6, bezier = "whimsy_bounce",   style = "popin 85%" })
    hl.animation({ leaf = "windowsIn",     enabled = true, speed = 6, bezier = "whimsy_bounce",   style = "popin 85%" })
    hl.animation({ leaf = "windowsOut",    enabled = true, speed = 5, bezier = "whimsy_float",    style = "popin 80%" })
    hl.animation({ leaf = "fadeIn",        enabled = true, speed = 4, bezier = "whimsy_soft" })
    hl.animation({ leaf = "fadeOut",       enabled = true, speed = 4, bezier = "whimsy_soft" })
    hl.animation({ leaf = "border",        enabled = true, speed = 8, bezier = "whimsy_overshoot" })
    hl.animation({ leaf = "layersIn",      enabled = true, speed = 5, bezier = "whimsy_float",  style = "slide" })
    hl.animation({ leaf = "layersOut",     enabled = true, speed = 4, bezier = "whimsy_glide" })
    hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 4, bezier = "whimsy_float" })
    hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 5, bezier = "whimsy_glide" })
    hl.animation({ leaf = "workspaces",    enabled = true, speed = 8, bezier = "whimsy_overshoot", style = "slidefadevert 18%" })
    hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 8, bezier = "whimsy_overshoot", style = "slidefadevert 18%" })
    hl.animation({ leaf = "workspacesOut", enabled = true, speed = 6, bezier = "whimsy_glide",     style = "slidefadevert 18%" })
else
    -- Snappy.
    hl.curve("snappy_out", { type = "bezier", points = { {0.15, 0.9}, {0.25, 1} } })
    hl.curve("snappy_in",  { type = "bezier", points = { {0.3, 0}, {0.6, 1} } })
    hl.animation({ leaf = "windows",       enabled = true, speed = 3, bezier = "snappy_out", style = "popin 80%" })
    hl.animation({ leaf = "windowsIn",     enabled = true, speed = 3, bezier = "snappy_out", style = "popin 80%" })
    hl.animation({ leaf = "windowsOut",    enabled = true, speed = 2, bezier = "snappy_in",  style = "popin 80%" })
    hl.animation({ leaf = "fadeIn",        enabled = true, speed = 2, bezier = "snappy_out" })
    hl.animation({ leaf = "fadeOut",       enabled = true, speed = 2, bezier = "snappy_in" })
    hl.animation({ leaf = "border",        enabled = true, speed = 4, bezier = "default" })
    hl.animation({ leaf = "workspaces",    enabled = true, speed = 3, bezier = "snappy_out", style = "slide" })
    hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 3, bezier = "snappy_out", style = "slide" })
    hl.animation({ leaf = "workspacesOut", enabled = true, speed = 2, bezier = "snappy_in",  style = "slide" })
    hl.animation({ leaf = "layers",        enabled = false })
end

-- --- Autostart --------------------------------------------------------------
hl.on("hyprland.start", function()
    hl.exec_cmd("sh -c 'command -v swww-daemon >/dev/null && exec swww-daemon --format xrgb; command -v awww-daemon >/dev/null && exec awww-daemon --format xrgb'")
    hl.exec_cmd("dbus-update-activation-environment --all")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("dunst")
    hl.exec_cmd("waybar")
    hl.exec_cmd(CONFIG .. "/hogwarts/scripts/apply-theme.sh")
end)

-- --- Window + layer rules ---------------------------------------------------
hl.window_rule({ name = "kitty-transparent", match = { class = "^kitty$" }, opacity = 0.82 })
hl.window_rule({ name = "zen-transparent",   match = { class = "^zen-browser$" }, opacity = 0.96 })
hl.window_rule({ name = "pavu-float",        match = { class = "^pavucontrol$" }, float = true })
hl.window_rule({ name = "pip",               match = { title = "^Picture-in-Picture$" }, float = true, pin = true })
hl.window_rule({ name = "no-shadow-tiled",   match = { float = false }, no_shadow = true })

-- Layer blur (the "stained glass" effect).
for _, ns in ipairs({ "waybar", "rofi", "dunst", "launcher", "gtk-layer-shell" }) do
    hl.layer_rule({ name = "blur-" .. ns, match = { namespace = "^" .. ns .. "$" }, blur = true, ignore_alpha = 0.5 })
end

-- --- Keybindings ------------------------------------------------------------
local M = "SUPER"

-- Essentials
hl.bind(M .. " + T",         hl.dsp.exec_cmd(terminal))
hl.bind(M .. " + Q",         hl.dsp.window.close())
hl.bind(M .. " + E",         hl.dsp.exec_cmd(fileManager))
hl.bind(M .. " + SLASH",     hl.dsp.exec_cmd(keybinds))
hl.bind(M .. " + SHIFT + S", hl.dsp.exec_cmd(settings))
hl.bind(M .. " + SHIFT + P", hl.dsp.exec_cmd(power))
hl.bind("CTRL + ALT + DELETE", hl.dsp.exec_cmd(power))
-- SUPER alone launches the app launcher (release bind)
hl.bind("SUPER", hl.dsp.exec_cmd(launcher), { release = true, non_consuming = true })

-- Window management
hl.bind(M .. " + F",        hl.dsp.window.float({ action = "toggle" }))
hl.bind(M .. " + SPACE",    hl.dsp.window.fullscreen({}))
hl.bind(M .. " + CTRL + P", hl.dsp.window.pin())
hl.bind(M .. " + left",     hl.dsp.focus({ direction = "left" }))
hl.bind(M .. " + right",    hl.dsp.focus({ direction = "right" }))
hl.bind(M .. " + up",       hl.dsp.focus({ direction = "up" }))
hl.bind(M .. " + down",     hl.dsp.focus({ direction = "down" }))
hl.bind(M .. " + SHIFT + left",  hl.dsp.window.swap({ direction = "left" }))
hl.bind(M .. " + SHIFT + right", hl.dsp.window.swap({ direction = "right" }))
hl.bind(M .. " + SHIFT + up",    hl.dsp.window.swap({ direction = "up" }))
hl.bind(M .. " + SHIFT + down",  hl.dsp.window.swap({ direction = "down" }))
hl.bind(M .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(M .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind(M .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(M .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))
hl.bind(M .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(M .. " + TAB", hl.dsp.focus({ workspace = "previous" }))

-- Workspaces 1-9: switch / silent-move / move+follow
for i = 1, 9 do
    hl.bind(M .. " + " .. i,             hl.dsp.focus({ workspace = i }))
    hl.bind(M .. " + ALT + " .. i,       hl.dsp.window.move({ workspace = i, silent = true }))
    hl.bind(M .. " + SHIFT + " .. i,     hl.dsp.window.move({ workspace = i }))
end

-- Session
hl.bind(M .. " + ALT + L",      hl.dsp.exec_cmd("loginctl lock-session"))
hl.bind(M .. " + SHIFT + R",    hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(M .. " + SHIFT + Q",    hl.dsp.exit())

-- Actions
hl.bind(M .. " + SHIFT + X", hl.dsp.exec_cmd('grim -g "$(slurp)" - | tee ~/Pictures/Screenshots/$(date +%Y%m%d-%H%M%S).png | wl-copy'))
hl.bind(M .. " + ALT + X",   hl.dsp.exec_cmd('grim - | tee ~/Pictures/Screenshots/$(date +%Y%m%d-%H%M%S).png | wl-copy'))
hl.bind(M .. " + ALT + C",   hl.dsp.exec_cmd("hyprpicker -a"))
hl.bind(M .. " + V",         hl.dsp.exec_cmd('cliphist list | rofi -dmenu -theme ' .. CONFIG .. '/rofi/menu.rasi -p Clipboard | cliphist decode | wl-copy'))
hl.bind(M .. " + ALT + E",   hl.dsp.exec_cmd(CONFIG .. "/rofi/scripts/emoji.sh"))

-- Media keys
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.4 @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl set +5%"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"),   { locked = true })
